on: # 触发条件
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # 部署分支
        TARGET_BRANCH: host-pages
        BUILD_SCRIPT: yarn global add node-gyp && yarn && yarn build
        # 打包输出目录
        BUILD_DIR: dist
